Repository Math-behind-AI/ScratchAI, pull requests merged in 2022-10, with the labels that each got.

#21 Added Word2Vec
  DL_algorithms/word2vec/word2vec.ipynb
Labels: hacktoberfest

#23 Added Decision Tree
  traditional_ML_algorithms/Decision Trees/Decision_Tree_from_scratch.ipynb
Labels: new layer/algo, hacktoberfest-accepted, hacktoberfest

#24 Added linear regression and svm scratch code
  traditional_ML_algorithms/svm algotrithm/svm_classifier_scratch_code.ipynb
Labels: documentation, enhancement, hacktoberfest
